<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>3.3.14</Version>
        <Description>极度不稳定，随时更新，谨慎使用。</Description>
        <PackageProjectUrl>https://github.com/FirstMelody/OccultCrescentHelper</PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
        <DalamudLibPath Condition="Exists('$(DALAMUD_HOME)/Dalamud.dll')">$(DALAMUD_HOME)/</DalamudLibPath>
        <DalamudLibPath Condition="'$(DALAMUD_HOME)' == '' AND Exists('$(appdata)\XIVLauncherCN\addon\Hooks\dev\Dalamud.dll')">$(appdata)\XIVLauncherCN\addon\Hooks\dev\</DalamudLibPath>
        <DalamudLibPath Condition="'$(DalamudLibPath)' == ''">$(appdata)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
        <AssemblySearchPaths>$(AssemblySearchPaths);$(DalamudLibPath)</AssemblySearchPaths>
        <NoWarn>$(NoWarn);4014</NoWarn>
        <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=$(MSBuildProjectName)/</PathMap>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants>DEBUG;TRACE;DEBUG_BUILD</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Release_CN'">
        <DefineConstants>RELEASE;TRACE;DALAMUD_CN</DefineConstants>
    </PropertyGroup>
    <!-- Files -->
    <ItemGroup>
        <Content Include="..\assets\icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
        <None Include="..\Translations\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <Link>Translations\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </None>
        <None Include="..\Data\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <Link>Data\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </None>
        <None Include="..\TelemetryServer\wwwroot\maps\linker-markers.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <Link>Data\NorthHorn\linker_markers.json</Link>
        </None>
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <ProjectReference Include="../Ocelot/Ocelot/Ocelot.csproj"/>
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <PackageReference Include="FFXIVOcelot" Version="1.1.5"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Pictomancy" Version="1.0.10" />
        <PackageReference Include="TextCopy" Version="6.2.1"/>
    </ItemGroup>
</Project>
